site_name: SFEIR Institute - dbt

theme:
  name: readthedocs
  titles_only: true
  navigation_depth: 2
  collapse_navigation: true
  highlightjs: true
  hljs_languages:
    - yaml
    - sql
    - python


nav:
  - 'index.md'
  - 'Module 3':
      - 'Lab 3.1':
        - 'Tasks': 'module_03/lab-1/README.md'
        - 'Solution': 'module_03/lab-1/SOLUTION.md'

  - 'Module 4':
      - 'Lab 4.1':
        - 'Tasks' : 'module_04/lab-1/README.md'
        - 'Solution' : 'module_04/lab-1/SOLUTION.md'
      - 'Lab 4.2':
        - 'Tasks' : 'module_04/lab-2/README.md'
        - 'Solution' : 'module_04/lab-2/SOLUTION.md'

  - 'Module 5':
      - 'Lab 5.1':
        - 'Tasks': 'module_05/lab-1/README.md'
        - 'Solution': 'module_05/lab-1/SOLUTION.md'

  - 'Module 6':
      - 'Lab 6.1':
        - 'Tasks': 'module_06/lab-1/README.md'
        - 'Solution': 'module_06/lab-1/SOLUTION.md'

  - 'Module 7':
      - 'Lab 7.1':
        - 'Tasks': 'module_07/lab-1/README.md'
        - 'Solution': 'module_07/lab-1/SOLUTION.md'

  - 'Module 8':
      - 'Lab 8.1':
        - 'Tasks': 'module_08/lab-1/README.md'
        - 'Solution': 'module_08/lab-1/SOLUTION.md'

  - 'Module 9':
      - 'Lab 9.1':
        - 'Tasks': 'module_09/lab-1/README.md'
        - 'Solution': 'module_09/lab-1/SOLUTION.md'

  - 'Module 10':
      - 'Lab 10.1':
        - 'Tasks': 'module_10/lab-1/README.md'
        - 'Solution': 'module_10/lab-1/SOLUTION.md'

  - 'Module 11':
      - 'Lab 11.1':
        - 'Tasks': 'module_11/lab-1/README.md'
        - 'Solution': 'module_11/lab-1/SOLUTION.md'

  - 'Module 12':
      - 'Lab 12.1':
        - 'Tasks': 'module_12/lab-1/README.md'
        - 'Solution': 'module_12/lab-1/SOLUTION.md'